#!/usr/bin/python

import argparse

def new_issue(message):
    pass

def list_issues():
    pass

def close_issue(number):
    pass

commands = {"new": new_issue, "list": list_issues, "close": close_issue}

parser = argparse.ArgumentParser(description="Simple issue handler")
parser.add_argument("command", default=-1, metavar="COMMAND", choices=commands,
        help="One of valid commands")
parser.add_argument("-m", "--message", default="",
        help="Message for NEW command")
parser.add_argument("number", required=False, type=int,
        help="Issue number for CLOSE command.")

args = parser.parse_args()
